import type { AppState } from "../types";

export const FIRM_NAME = "Okoye, Bello & Co.";
export const FIRM_ADDRESS = "14 Boyle Street, Onikan, Lagos";
export const FIRM_EMAIL = "accounts@okoyebello.ng";
export const FIRM_PHONE = "+234 1 700 4410";

export function seedState(): AppState {
  return {
    lawyers: [
      {
        id: "LYR-001",
        name: "Adaeze Okoye",
        email: "adaeze.okoye@okoyebello.ng",
        phone: "+234 803 110 2201",
        role: "partner",
        practiceAreas: ["divorce", "civil"],
        createdAt: "2025-11-02T09:00:00.000Z",
      },
      {
        id: "LYR-002",
        name: "Ibrahim Bello",
        email: "ibrahim.bello@okoyebello.ng",
        phone: "+234 802 441 9088",
        role: "partner",
        practiceAreas: ["criminal", "business"],
        createdAt: "2025-11-02T09:00:00.000Z",
      },
      {
        id: "LYR-003",
        name: "Chioma Eze",
        email: "chioma.eze@okoyebello.ng",
        phone: "+234 809 220 1144",
        role: "associate",
        practiceAreas: ["business", "civil"],
        createdAt: "2026-01-14T10:15:00.000Z",
      },
    ],
    clients: [
      {
        id: "CLT-2026-0001",
        name: "Ngozi Adeyemi",
        address: "8 Bourdillon Road, Ikoyi, Lagos",
        email: "ngozi.adeyemi@mail.com",
        phone: "+234 701 445 8821",
        createdAt: "2026-01-12T11:20:00.000Z",
      },
      {
        id: "CLT-2026-0002",
        name: "Harbourline Logistics Ltd",
        address: "Wharf Road, Apapa, Lagos",
        email: "legal@harbourline.ng",
        phone: "+234 1 454 2200",
        createdAt: "2026-03-04T08:40:00.000Z",
      },
      {
        id: "CLT-2026-0003",
        name: "Chinedu Okafor",
        address: "21 Adeniran Ogunsanya, Surulere, Lagos",
        email: "chinedu.okafor@gmail.com",
        phone: "+234 806 331 7702",
        createdAt: "2026-09-10T15:05:00.000Z",
      },
    ],
    matters: [
      {
        id: "CASE-2026-0001",
        clientId: "CLT-2026-0001",
        category: "divorce",
        title: "Adeyemi v Adeyemi — dissolution and settlement",
        assignedLawyerId: "LYR-001",
        conflictCleared: true,
        engagementAcknowledged: true,
        memo: "Client instructs for dissolution on two years' separation. Two children. Matrimonial home in Lekki Phase 1. Settlement preferred on maintenance; custody disputed.",
        minutes:
          "12 Jan 2026 — First conference at chambers. Client produced marriage certificate (2014), children's birth certificates, and title documents for the Lekki house. Instructed to file at Ikeja Family Division.",
        actionPoints:
          "1. File petition and motion on notice for interim maintenance.\n2. Serve respondent through last known address at Victoria Island.\n3. Diary 2 Oct 2026 hearing and prepare court memo.",
        courtCaseNumber: "LD/1234/2026",
        status: "in_court",
        parties: [
          {
            id: "pty-1",
            role: "client",
            name: "Ngozi Adeyemi",
            email: "ngozi.adeyemi@mail.com",
            phone: "+234 701 445 8821",
          },
          {
            id: "pty-2",
            role: "opposing_party",
            name: "Kunle Adeyemi",
            email: "kunle.adeyemi@outlook.com",
            phone: "+234 809 118 4400",
          },
          {
            id: "pty-3",
            role: "opposing_counsel",
            name: "Femi Ajayi & Co.",
            email: "femi@ajayilaw.ng",
            phone: "+234 1 270 3340",
          },
          {
            id: "pty-4",
            role: "court",
            name: "High Court of Lagos State, Ikeja Family Division",
            email: "",
            phone: "",
          },
        ],
        createdAt: "2026-01-12T11:40:00.000Z",
      },
      {
        id: "CASE-2026-0002",
        clientId: "CLT-2026-0002",
        category: "business",
        title: "Harbourline v Apex Terminals — demurrage and detention",
        assignedLawyerId: "LYR-002",
        conflictCleared: true,
        engagementAcknowledged: true,
        memo: "Claim for unpaid demurrage and container detention arising from a 2025 terminal contract. Claimant seeks ₦48m plus interest. Settlement window still open.",
        minutes:
          "4 Mar 2026 — Conference with GC. Contract, invoices, and terminal logs reviewed. Instruction: letter before action, then writ if no payment in 14 days.",
        actionPoints:
          "1. Demand letter already issued.\n2. Writ filed; await defence.\n3. Prepare case management conference bundle.",
        courtCaseNumber: "LD/8841/2026",
        status: "active",
        parties: [
          {
            id: "pty-5",
            role: "client",
            name: "Harbourline Logistics Ltd",
            email: "legal@harbourline.ng",
            phone: "+234 1 454 2200",
          },
          {
            id: "pty-6",
            role: "opposing_party",
            name: "Apex Terminals Ltd",
            email: "counsel@apexterminals.ng",
            phone: "+234 1 461 9001",
          },
        ],
        createdAt: "2026-03-04T09:10:00.000Z",
      },
      {
        id: "CASE-2026-0003",
        clientId: "CLT-2026-0003",
        category: "criminal",
        title: "FRN v Okafor — obtaining by false pretences",
        assignedLawyerId: "LYR-002",
        conflictCleared: true,
        engagementAcknowledged: true,
        memo: "Client charged at Magistrate Court, Yaba. Alleges a commercial dispute dressed as a criminal complaint. Bail already granted. Instruction is defence and possible civil counterclaim later.",
        minutes:
          "10 Sep 2026 — Intake with client's brother present. Charge sheet and bail bond collected. Next mention not yet fixed.",
        actionPoints:
          "1. Obtain certified charge sheet and extra copies of statements.\n2. Write prosecutor for disclosure.\n3. Hold second conference before next mention.",
        courtCaseNumber: "",
        status: "intake",
        parties: [
          {
            id: "pty-7",
            role: "client",
            name: "Chinedu Okafor",
            email: "chinedu.okafor@gmail.com",
            phone: "+234 806 331 7702",
          },
          {
            id: "pty-8",
            role: "court",
            name: "Magistrate Court, Yaba",
            email: "",
            phone: "",
          },
        ],
        createdAt: "2026-09-10T15:20:00.000Z",
      },
    ],
    documents: [
      {
        id: "DOC-001",
        matterId: "CASE-2026-0001",
        name: "Petition for dissolution.pdf",
        kind: "Court filing",
        source: "upload",
        url: "",
        sizeLabel: "420 KB",
        uploadedAt: "2026-01-18T14:00:00.000Z",
      },
      {
        id: "DOC-002",
        matterId: "CASE-2026-0001",
        name: "Hearing notice — 2 Oct 2026",
        kind: "Hearing notice",
        source: "url",
        url: "https://lagoscomis.lagosjudiciary.gov.ng",
        sizeLabel: "URL",
        uploadedAt: "2026-09-18T09:30:00.000Z",
      },
      {
        id: "DOC-003",
        matterId: "CASE-2026-0002",
        name: "Letter before action — Apex Terminals.pdf",
        kind: "Demand letter",
        source: "upload",
        url: "",
        sizeLabel: "188 KB",
        uploadedAt: "2026-03-06T16:12:00.000Z",
      },
    ],
    actions: [
      {
        id: "ACT-001",
        matterId: "CASE-2026-0001",
        type: "file_court_action",
        notes: "Petition and originating processes filed at Ikeja. Suit number LD/1234/2026 allocated.",
        documentId: "DOC-001",
        emailOtherParty: false,
        otherPartyEmail: "",
        cost: 45_000,
        createdAt: "2026-01-18T14:10:00.000Z",
      },
      {
        id: "ACT-002",
        matterId: "CASE-2026-0002",
        type: "demand_letter",
        notes: "Fourteen-day demand. Copied to Apex in-house counsel.",
        documentId: "DOC-003",
        emailOtherParty: true,
        otherPartyEmail: "counsel@apexterminals.ng",
        cost: 0,
        createdAt: "2026-03-06T16:20:00.000Z",
      },
    ],
    hearings: [
      {
        id: "HRG-001",
        matterId: "CASE-2026-0001",
        date: "2026-10-02",
        time: "09:30",
        court: "High Court of Lagos State, Ikeja — Court 7",
        memo: "Continuation of hearing. Witness 1 (petitioner) still in chief. Bring original title documents.",
        hearingNotice: "Hearing notice dated 18 Sep 2026.",
        reminderSent: true,
        outcome: "",
        outcomeNotes: "",
        nextDate: "",
        invoiceId: "INV-2026-0002",
      },
      {
        id: "HRG-002",
        matterId: "CASE-2026-0002",
        date: "2026-10-14",
        time: "11:00",
        court: "High Court of Lagos State, Lagos — Commercial Court 3",
        memo: "Case management conference. Agreed issues and timetable.",
        hearingNotice: "CMC notice served on both counsel.",
        reminderSent: false,
        outcome: "",
        outcomeNotes: "",
        nextDate: "",
        invoiceId: "",
      },
    ],
    invoices: [
      {
        id: "INV-2026-0001",
        matterId: "CASE-2026-0001",
        clientId: "CLT-2026-0001",
        type: "sign_on",
        description: "Sign-on fee — Divorce",
        amount: 250_000,
        status: "paid",
        issuedAt: "2026-01-12T11:45:00.000Z",
        paidAt: "2026-01-14T10:00:00.000Z",
        emailedTo: "ngozi.adeyemi@mail.com",
      },
      {
        id: "INV-2026-0002",
        matterId: "CASE-2026-0001",
        clientId: "CLT-2026-0001",
        type: "appearance",
        description: "Court appearance — 2 Oct 2026, Ikeja Court 7",
        amount: 75_000,
        status: "sent",
        issuedAt: "2026-09-20T08:00:00.000Z",
        paidAt: "",
        emailedTo: "ngozi.adeyemi@mail.com",
      },
      {
        id: "INV-2026-0003",
        matterId: "CASE-2026-0002",
        clientId: "CLT-2026-0002",
        type: "sign_on",
        description: "Sign-on fee — Business Matter",
        amount: 350_000,
        status: "sent",
        issuedAt: "2026-03-04T09:15:00.000Z",
        paidAt: "",
        emailedTo: "legal@harbourline.ng",
      },
      {
        id: "INV-2026-0004",
        matterId: "CASE-2026-0003",
        clientId: "CLT-2026-0003",
        type: "sign_on",
        description: "Sign-on fee — Criminal Matter",
        amount: 300_000,
        status: "draft",
        issuedAt: "2026-09-10T15:25:00.000Z",
        paidAt: "",
        emailedTo: "",
      },
    ],
    communications: [
      {
        id: "com-1",
        matterId: "CASE-2026-0001",
        channel: "email",
        subject: "Invoice INV-2026-0001 sent",
        body: "Sign-on invoice emailed to ngozi.adeyemi@mail.com.",
        at: "2026-01-12T11:46:00.000Z",
      },
      {
        id: "com-2",
        matterId: "CASE-2026-0001",
        channel: "email",
        subject: "Hearing reminder — 2 Oct 2026",
        body: "Reminder sent to Adaeze Okoye with case details, court, and time.",
        at: "2026-09-25T07:00:00.000Z",
      },
    ],
    audit: [
      {
        id: "aud-1",
        at: "2026-01-12T11:20:00.000Z",
        actor: "Chambers clerk",
        action: "Created client CLT-2026-0001 Ngozi Adeyemi",
        entityType: "client",
        entityId: "CLT-2026-0001",
      },
      {
        id: "aud-2",
        at: "2026-01-12T11:40:00.000Z",
        actor: "Adaeze Okoye",
        action: "Opened matter CASE-2026-0001 after conflict check and engagement",
        entityType: "matter",
        entityId: "CASE-2026-0001",
      },
      {
        id: "aud-3",
        at: "2026-01-14T10:00:00.000Z",
        actor: "Accounts",
        action: "Recorded payment on INV-2026-0001",
        entityType: "invoice",
        entityId: "INV-2026-0001",
      },
      {
        id: "aud-4",
        at: "2026-03-04T09:10:00.000Z",
        actor: "Ibrahim Bello",
        action: "Opened matter CASE-2026-0002",
        entityType: "matter",
        entityId: "CASE-2026-0002",
      },
    ],
    notices: [],
  };
}
